Add coffee-rails again
Because deploy failed at `rake assets:precompile`:

```
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       I, [2023-11-24T07:02:48.170771 #377]  INFO -- : [Rollbar] Scheduling item
       I, [2023-11-24T07:02:48.170881 #377]  INFO -- : [Rollbar] Sending item
       I, [2023-11-24T07:02:48.171442 #377]  INFO -- : [Rollbar] Sending json
       rake aborted!
       LoadError: cannot load such file -- coffee_script
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/autoload/coffee_script.rb:2:in `<main>'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/coffee_script_processor.rb:17:in `cache_key'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:102:in `processor_cache_key'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:111:in `block in processors_cache_keys'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:111:in `map'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:111:in `processors_cache_keys'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:37:in `cache_key'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:102:in `processor_cache_key'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:49:in `block in processor_cache_key'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:49:in `processor_cache_key'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:111:in `block in processors_cache_keys'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:111:in `map'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processor_utils.rb:111:in `processors_cache_keys'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/processing.rb:165:in `resolve_processors_cache_key_uri'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets.rb:216:in `block in <module:Sprockets>'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/dependencies.rb:68:in `resolve_dependency'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:54:in `block in resolve_dependency'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:54:in `resolve_dependency'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:290:in `block in resolve_dependencies'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:290:in `map'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:290:in `resolve_dependencies'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:54:in `block in load'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:333:in `block in fetch_asset_from_dependency_cache'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:329:in `each'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:329:in `each_with_index'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:329:in `fetch_asset_from_dependency_cache'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/loader.rb:43:in `load'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `block in load'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:207:in `block in fetch_or_store'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:187:in `fetch'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/map.rb:206:in `fetch_or_store'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/cached_environment.rb:44:in `load'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:81:in `find_asset'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/base.rb:88:in `find_all_linked_assets'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `each'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `to_a'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/sprockets-4.2.1/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
       /tmp/build/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
```